### ISSUE TITLE
Reverse DNS no longer works

### ISSUE THREAD

**Issue by pduchnovsky** [dougbw/coredns_omada#65]
Hey, I ran the following version `@sha256:f95d7d342bdd82c2625a4c9313ae83d0a79db917501ba878e15b50b82b1f9b09` for a while and decided to upgrade today, but since then it stopped working for reverse dns queries completely.

My Corefile:
```
. {
    health :8080
    omada {
        controller_url {$OMADA_URL}
        site {$OMADA_SITE}
        username {$OMADA_USERNAME}
        password {$OMADA_PASSWORD}
        refresh_minutes 1
    }
    rewrite stop {
        name suffix .arpa .arpa
        answer name auto
        answer value (.*)\.docker_.*\. {1}.
    }
    forward 20.172.in-addr.arpa 127.0.0.11
}
```

My docker-compose:
```
  coredns:
    image: ghcr.io/dougbw/coredns_omada
    container_name: coredns
    ports:
      - 127.0.0.1:5053:53/udp
    environment:
      - TZ=Europe/Amsterdam
      - OMADA_URL=https://server.lan:8043
      - OMADA_SITE=Default
      - OMADA_USERNAME=${OMADA_USERNAME}
      - OMADA_PASSWORD=${OMADA_PASSWORD}
      - OMADA_DISABLE_HTTPS_VERIFICATION=true
    volumes:
      - /volume1/docker/coredns/Corefile:/Corefile
    restart: always
    mem_limit: 100m
    memswap_limit: 100m
    security_opt:
      - no-new-privileges:true
```

With version `@sha256:f95d7d342bdd82c2625a4c9313ae83d0a79db917501ba878e15b50b82b1f9b09`:
```
/opt/adguardhome/work # nslookup 10.10.10.222 127.0.0.1:5053
Server:         127.0.0.1:5053
Address:        127.0.0.1:5053

222.10.10.10.in-addr.arpa       name = pd-work
```

With latest:
```
/opt/adguardhome/work # nslookup 10.10.10.222 127.0.0.1:5053
Server:         127.0.0.1:5053
Address:        127.0.0.1:5053

** server can't find 222.10.10.10.in-addr.arpa: SERVFAIL
```
